package ru.maluginp.transpiler.swift

import ru.maluginp.transpiler.convertors.*

class SwiftTranspiler : Transpiler {
    override fun format(el: TrElement): String = when (el) {
        is TrPackage -> SwiftTrPackage(el)
        is TrImport -> SwiftTrImport(el)
        is TrIf -> SwiftTrIf(el)
        is TrFor -> SwiftTrFor(el)
        is TrFunc -> SwiftTrFunc(el)
        is TrBinaryOp -> SwiftTrBinaryOp(el)
        is TrUnaryOp -> SwiftTrUnaryOp(el)
        is TrWhile -> SwiftTrWhile(el)
        is TrThrow -> SwiftTrThrow(el)
        is TrReturn -> SwiftTrReturn(el)
        is TrCall -> SwiftTrCall(el)
        is TrCallLambda -> SwiftTrCallLambda(el)
        is TrInterface -> SwiftTrInterface(el)
        is TrClass -> SwiftTrClass(el)
        is TrParent -> SwiftTrParent(el)
        is TrMember -> SwiftTrMember(el)
        is TrObject -> SwiftTrObject(el)
        is TrCompanionObject -> SwiftTrCompanionObject(el)
        is TrEnumClass -> SwiftTrEnumClass(el)
        is TrExprConst -> SwiftTrExprConst(el)
        is TrExprTypeOp -> SwiftTrExprTypeOp(el)
        is TrExprSuper -> SwiftTrExprSuper(el)
        is TrExprThis -> SwiftTrExprThis(el)
        is TrExprContinue -> SwiftTrExprContinue(el)
        is TrExprBreak -> SwiftTrExprBreak(el)
        is TrExprObject -> SwiftTrExprObject(el)
        is TrExprWhen -> SwiftTrExprWhen(el)
        is TrExprWhenEntry -> SwiftTrExprWhenEntry(el)
        is TrExprWhenEntryConditionIn -> SwiftTrExprWhenEntryConditionIn(el)
        is TrExprWhenEntryConditionIs -> SwiftTrExprWhenEntryConditionIs(el)
        is TrExprWhenEntryCondition -> SwiftTrExprWhenEntryCondition(el)
        is TrExprLabeled -> SwiftTrExprLabeled(el)
        is TrExprName -> SwiftTrExprName(el)
        is TrExprProperty -> SwiftTrExprProperty(el)
        is TrPropertyVar -> SwiftTrPropertyVar(el)
        is TrTypeAlias -> SwiftTrTypeAlias(el)
        is TrTypeParam -> SwiftTrTypeParam(el)
        is TrInitBlock -> SwiftTrInitBlock(el)
        is TrEnum -> SwiftTrEnum(el)
        is TrValueArg -> SwiftTrValueArg(el)
        is TrModifier -> SwiftTrModifier(el)
        is TrModifierKeyword -> SwiftTrModifierKeyword(el)
        is TrFuncParam -> SwiftTrFuncParam(el)
        is TrProperty -> SwiftTrProperty(el)
        is TrBlock -> SwiftTrBlock(el)
        is TrStatement -> SwiftTrStatement(el)
        is TrExprBrace -> SwiftTrExprBrace(el)
        is TrExprBraceParam -> SwiftTrExprBraceParam(el)
        is TrAnnotationSet -> SwiftTrAnnotationSet(el)
        is TrAnnotation -> SwiftTrAnnotation(el)
        is TrTypeRefNullable -> SwiftTrTypeRefNullable(el)
        is TrTypeRefDynamic -> SwiftTrTypeRefDynamic(el)
        is TrTypeRefPiece -> SwiftTrTypeRefPiece(el)
        is TrTypeRef -> SwiftTrTypeRef(el)
        is TrTypeRefFunc -> SwiftTrTypeRefFunc(el)
        is TrTypeRefFuncParam -> SwiftTrTypeRefFuncParam(el)
        is TrExprArrayAccess -> SwiftTrExprArrayAccess(el)
        is TrExprCollLit -> SwiftTrExprCollLit(el)
        is TrExprAnnotated -> SwiftTrExprAnnotated(el)
        is TrExprStringTmpl -> SwiftTrExprStringTmpl(el)
        is TrTry -> SwiftTrTry(el)
        is TrCatch -> SwiftTrCatch(el)
        is TrImplementation -> SwiftTrImplementation(el)
        else -> SwiftTrEmpty()
    }.let(TrImplementation::output)
}